schema_version = "1.0.0"
id = "chemblender"
version = "2.4.0"
name = "ChemBlender"
tagline = "Scientific results, structures and fields for Blender"
maintainer = "LiHaodong"
type = "add-on"
website = "https://www.chemblender.com"
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]
platforms = ["windows-x64"]
wheels = [
  "./wheels/rdkit-2026.3.3-cp313-cp313-win_amd64.whl",
  "./wheels/gemmi-0.7.5-cp313-cp313-win_amd64.whl",
]

[permissions]
files = "Read CBQ projects and save caches, images and project data"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.zip",
  "scripts/",
  "tests/",
]
